RC
DCMLab/dimcat pull request #1
Opened 2022-05-12 20:16 UTC by johentsch

Hi @apmcleod, 

The interface is mostly as we discussed and working fine for current use cases. These can be seen in `test_analyzer.py` and in the [data_reports/generate.ipynb](https://github.com/DCMLab/data_reports/blob/main/generate.ipynb) notebook that demonstrates unigram and bigram creation
* for the entire dataset
* for corpus groups
* piece-wise

TODO: changelog to be updated

2022-05-23 09:28 UTC, apmcleod commented
I cloned unittest_metacorpus and pleyel into ~, but all tests fail with `ValueError: No data has been loaded.` when I run `pytest` from the command line. Any ideas?

2022-05-23 16:10 UTC, apmcleod requested changes
This looks amazing! The notebook runs smoothly, and the user-facing interface seems very clean to me.

I left a number of comments. I also have 4 general questions/comments here:
- I think tests/test_skeleton.py can be removed?
- I get a lot of pandas errors about using Series.append (to be deprecated; should be concat). I guess they might be coming from ms3, the code it complains about is this (no line number given): `res = res.append(pd.Series([last_val], index=['end']))`
- In the notebook, why does localkey_slices not produce "intervals" but mode_slices does? Is that correct?
- In general, in-line comments would be extremely helpful in every process_data function (and elsewhere, but mainly process_data). process_data tends to be pretty dense and do a lot of non-obvious indexing.

A lot of these questions/comments are just things to note/questions to discuss, while some are easily changed, I think. Feel free to reply, ask me to change some of these, or change them yourself. Also, feel free to push some of the comments to Issues for future changes. But before merge, I think at least the in-line comments and docs should be complete.
-

2022-05-23 16:10 UTC, apmcleod commented on src/dimcat/grouper.py
> +        return index[0]
Is this always true? E.g., if some slicer comes first, will index[0] by "corpus"?

2022-05-23 16:10 UTC, apmcleod commented on src/dimcat/grouper.py
> +            print("Need LocalKeyGrouper")
LocalKeySlicer (actually, will this ever run anyways?)

2022-05-23 16:10 UTC, apmcleod commented on src/dimcat/slicer.py
> +        assert (
I like the pattern (a la Grouper, Analyzer, ) where process_data is defined in super() and the computation is done in some separate func (like Analyzer.compute()). It looks like the basic structure of this loop should be possible to do that with as well here.

2022-05-23 16:10 UTC, apmcleod commented on src/dimcat/utils.py
> +from typing import Collection
Add a short file-level doc here.

2022-05-23 16:10 UTC, apmcleod commented on src/dimcat/writer.py
Docs missing in this file: file-level, class-level, __init__-level.

2022-05-23 16:10 UTC, apmcleod commented on src/dimcat/writer.py
>  class TSVwriter(PipelineStep):
Or TsvWriter

2022-06-16 11:49 UTC, johentsch commented on src/dimcat/analyzer.py
>      def compute(
> How do we pass these params here, within a pipeline?

All pipeline steps are initialized and parametrized when their sequence is being defined, e.g. `Pipeline([CorpusGrouper(), ChordSymbolUnigrams(once_per_group=True)])`.

> May be better to include these in the Analyzer constructor? 

How do you mean?

> This would make compute no longer static.

I think we wanted to have compute static so that it can be used independently of the pipeline step object. If compute takes parameters, the parametrization will be stored within the object.

Not sure I've understood you correctly?

2022-06-16 11:56 UTC, johentsch commented
> I think tests/test_skeleton.py can be removed?

Done.

> I get a lot of pandas errors about using Series.append (to be deprecated; should be concat). I guess they might be coming from ms3, the code it complains about is this (no line number given): `res = res.append(pd.Series([last_val], index=['end']))`

Right, this is fixed in the upcoming version of ms3.

> In the notebook, why does localkey_slices not produce "intervals" but mode_slices does? Is that correct?

I couldn't find the spot in the notebook where you see this. Had a quick look into `localkey_slices.sliced` and `mode_slices.sliced` and both seemed to have the required intervals?

> In general, in-line comments would be extremely helpful in every process_data function (and elsewhere, but mainly process_data). process_data tends to be pretty dense and do a lot of non-obvious indexing.

Yes, I agree. Will add those.

2022-06-17 11:56 UTC, apmcleod commented on src/dimcat/analyzer.py
>      def compute(
I think you got the main idea. What I'm saying is I don't see a clean way to set these parameters (`pitch_class_format`, `normalize`, etc.) from within a Pipeline. It would be much more natural to instead pass them through to the Analyzer constructor when creating the Pipeline.

We can still keep this computation static (though I don't recall that discussion), for example by defining:

```
def compute(self, notes):
    PitchClassVectors.get_pcvs(notes, pitch_class_format=self.pitch_class_format, ...)
```

And then having a new static `get_pcvs` perform the actual computation.

2022-06-17 12:43 UTC, apmcleod commented
> I couldn't find the spot in the notebook where you see this. Had a quick look into `localkey_slices.sliced` and `mode_slices.sliced` and both seemed to have the required intervals?

Couldn't find it now, not sure what I was talking about.

2022-06-17 12:46 UTC, apmcleod commented on src/dimcat/slicer.py
> +                    segmented = segment_by_adjacency_groups(
This line throws a KeyError (via ms3) when some data has Nans for its localkey column. For example, currently: https://github.com/DCMLab/frescobaldi_fiori_musicali/blob/5c036b3ffb510ced77050437df370d106dd98419/harmonies/12.16_Toccata_cromaticha_per_l%E2%80%99elevatione_phrygian.tsv

2022-06-17 14:24 UTC, apmcleod commented on src/dimcat/analyzer.py
>      def compute(
Oh, I think I see this is done via self.config actually?

2022-06-17 15:21 UTC, johentsch reviewed
Tried to address all comments. Let me know if there are more docstrings or in-line comments needed.

2022-06-17 16:20 UTC, apmcleod reviewed
All looks good to me for now. There is one remaining comment about the 2 unused params in `PitchClassVectors.compute`, but after that (or if you have a reason to leave them there), feel free to merge.

I added all remaining comments to issues. I may go through more closely in future weeks for some optimizations or other small changes (I saw a couple of places where a list generator could be used instead of a for loop I think). But this can be in a future, small PR.

2022-06-20 15:59 UTC, merged